<?php
/**
 *
 * @file BaiduHmWidget.php
 * @author shangheguang <shangheguang@yuanxin-inc.com>
 * @version 2.0
 * @date 2018-03-27
 */

namespace common\widgets;

use yii\bootstrap\Widget;
use yii\web\Cookie;
use yii\web\View;

class BaiduStatisticsWidget extends Widget
{
    public $controller;
    public function run()
    {

        parent::run(); // TODO: Change the autogenerated stub
        if (strpos($this->controller->module->controllerNamespace, 'mobile')!==false) {
            $key='m.nisiya.top';
        }
        if (strpos($this->controller->module->controllerNamespace, 'pc')!==false) {
            $key='www.nisiya.top';
        }

        $code = '';

        //如果存在key
        if (isset($key) && YII_ENV == 'prod') {
            $code .= $this->getnisiyaStatisticsCode($key);
        }

        //如果存在key
//        if (isset($key) && isset(\Yii::$app->params['baidu_statistics'][$key]) && YII_ENV == 'prod'){
//            //当是小程序时，不适用百度统计
//            $key=\Yii::$app->params['baidu_statistics'][$key];
//            $code.=$this->getStatisticsCode($key);
//        }

        $this->view->registerJs($code,View::POS_END);

    }

    /**
     * 百度统计代码
     * @author shangheguang <shangheguang@yuanxin-inc.com>
     * @date 2020-04-07
     * @param int $key key
     * @return string
     */
    public function getStatisticsCode($key)
    {
        $content=<<<content
(function() {
        if(window.__wxjs_environment !== 'miniprogram'){
            var _hmt = _hmt || [];
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?{$key}";
            var s = document.getElementsByTagName("script")[0]; 
            s.parentNode.insertBefore(hm, s);
        }
})();
content;
        return $content;
    }

    /**
     * 王氏统计代码
     * @author shangheguang <shangheguang@yuanxin-inc.com>
     * @date 2020-04-07
     * @param int $key key
     * @return string
     */
    public function getnisiyaStatisticsCode($key)
    {
        //记录来源
        $paramName = 'from_channel';
        $from_channel = \Yii::$app->request->getQueryParam($paramName, '');
        if (!empty($from_channel)) {
            $cookies = \Yii::$app->response->cookies;
            $cookies->add(new Cookie([
                'name' => $paramName,
                'value' => $from_channel,
                'expire' => time() + 3600 * 24,
                'domain' => 'nisiya.top',
                'httpOnly' => false,
            ]));
        } else {
            $cookies = \Yii::$app->request->cookies;
            $from_channel = $cookies->get($paramName, '');
        }

        $content=<<<content
        var _maq = _maq || {};
        _maq = {site:'{$key}',from_channel:'{$from_channel}'};    
    (function() {
        var ma = document.createElement('script'); 
        ma.type = 'text/javascript'; 
        ma.async = true;
        ma.src = 'https://dc.nisiya.top/miao.js';
        var s = document.getElementsByTagName('script')[0]; 
        s.parentNode.insertBefore(ma, s);
    })();
content;
        return $content;
    }

}
