<?php
/**
 * 基类控制器
 * @file CommonController.php
 * @author shangheguang <shangheguang@yuanxin-inc.com>
 * @version 1.0
 * @date 2018-08-31
 */

namespace api\controllers;

use api\behaviors\AesChecker;
use api\behaviors\ApiCheckerBehavior;
use yii\web\Controller;
use yii\web\Response;

class CommonController extends Controller
{
    protected $requestID;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->requestID = $this->getRequestID();
        header("X-REQUEST-ID:".$this->requestID);
    }

    public function behaviors()
    {
        return [
            'class'=>ApiCheckerBehavior::class
        ];
    }

    /**
     * 设置唯一的请求ID
     * @return string
     */
    private function getRequestID()
    {
        return md5(uniqid() . microtime() . mt_rand(111111, 999999));
    }

    /**
     * 返回成功的json数据
     * @param array $data
     * @param string $msg
     * @return array
     */
    protected function jsonSuccess($data = [], $msg = 'success')
    {
        $return['request_id'] = $this->requestID;
        $return['code'] = 200;
        $return['msg'] = $msg;
        $return['data'] = $data;
        return $this->jsonOutputCore($return);
    }

    /**
     * 返回失败的json数据
     * @param string $msg
     * @param int $code
     * @return array
     */
    protected function jsonError($msg = '', $code = 400)
    {
        $return['request_id'] = $this->requestID;
        $return['code'] = $code;
        $return['msg'] = $msg;
        $return['data'] = (object)[];
        return $this->jsonOutputCore($return);
    }

    /**
     * json输出的核心
     * @param $data
     * @return array
     */
    protected function jsonOutputCore($data)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        //所有内容输出转换为字符型;
        array_walk_recursive($data['data'], function (&$value) {
            $value = strval($value);
        });
        return $data;
    }

}